config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  #typeahead
  get 'things/typeahead/:query' => 'things#typeahead'

#if someone makes a get request from patient/referrals#forpatient

  resources :patients do
    collection do
      # get 'home', :to => "patients/home"
      get 'check_referral', :to => "patients/check_referral"
      get 'pending_requests', :to => "patients/pending_requests"
      get 'account_settings', :to => "patients/account_settings"
      get 'show_referral', :to => "patients/show_referralrout"
    end
  end


  resources :doctors do
    collection do
      # get 'home', :to => "doctors/home"
      # get 'show', :to => "doctors/home"
      get 'create_referral', :to => "doctors/create_referral"
      get 'pending_requests', :to => "doctors/pending_requests"
      get 'account_settings', :to => "doctors/account_settings"
    end
    resources :referrals
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id              :integer          not null, primary key
#  name            :text
#  dob             :date
#  phone           :text
#  address         :text
#  medicare        :text
#  health_fund     :text
#  email           :text
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Patient < ApplicationRecord
  has_secure_password

  has_many :referrals
  has_many :doctors, :through => :referrals

  validates :email, :presence => true, :uniqueness => true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new patient_params

    if @patient.save
      redirect_to patient_path(session[:patient_id])
    else
      render :new
    end
  end

  def show
    @patient = Patient.find_by :id => session[:patient_id]
  end

  def edit
    @patient = Patient.find_by :id => session[:patient_id]
  end

  def update
    patient = Patient.find_by :id => session[:patient_id]
    patient.update patient_params
    redirect_to patient_path
  end

  # def home
  #   @patient = Patient.find_by :id => session[:patient_id]
  # end
  def check_referral

    @patient = Patient.find session[:patient_id]
    # raise 'hell'

  end

  def show_referral
    @referral = Referral.find params[:format]
    # raise 'hell'
  end

  def pending_requests

  end

  def account_settings
    @patient = Patient.find_by :id => session[:patient_id]
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :dob, :phone, :address, :medicare, :health_fund, :email, :password, :password_digest, :password_digest_confirmation)
  end

end

app/views/patients/account_settings.html.erb
<header class="patient-header">
  <h2>Account Settings</h2>

  <nav class="patient-nav">
    <%= link_to "Home", patient_path(session[:patient_id])%>
    <%= link_to "Your Referrals", check_referral_patients_path %>
    <%= link_to "Pending Requests", pending_requests_patients_path%>
    <%= link_to "Account Settings", account_settings_patients_path%>
    <%= link_to 'Sign Out', login_path, :method => 'delete' %>
  </nav>
</header>



<%= form_for @patient do | f | %>

  <fieldset class="form-group">
    <%= f.label :name  %>
    <%= f.text_field :name, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :dob %>
    <%= f.text_field :dob, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :medicare %>
    <%= f.text_field :medicare, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :health_fund %>
    <%= f.text_field :health_fund, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group fsubmit">
    <%= f.submit %>
  </fieldset>
<% end %>

<%= button_to 'Delete Account', patient_path(@patient.id), :method => 'delete', :class => "button-delete" %>

app/views/patients/check_referral.html.erb
<header class="patient-header">
  <h2>Referrals List</h2>

  <nav class="patient-nav">
    <%= link_to "Home", patient_path(session[:patient_id])%>
    <%= link_to "Your Referrals", check_referral_patients_path %>
    <%= link_to "Pending Requests", pending_requests_patients_path%>
    <%= link_to "Account Settings", account_settings_patients_path%>
    <%= link_to 'Sign Out', login_path, :method => 'delete' %>
  </nav>
</header>

<% @patient.referrals.each do | referral | %>

  <ul>

    <!-- <li>From: <%= referral.referrer.name %></li> -->
    <!-- <li><%= link_to "Referral from #{referral.referee.name}", show_referral_patients_path(referral.id) %></li> -->
    <div class="button-container-referral">
    <!-- Trigger the modal with a button -->
    <!-- <%= button_to 'Sign In', login_path, :data => {:toggle => "modal", :target => "#myModal"}, :class => "btn btn-info btn-lg"%> -->
    <button type="button" class="btn btn-info btn-lg ref-list-button" data-toggle="modal" data-target="#myModal<%= referral.id %>"><%= "#{referral.referee.name}" %></button>

    <!-- Modal -->
      <div class="modal fade" id="myModal<%= referral.id %>" role="dialog">
        <div class="modal-dialog">
        <!-- Modal content-->
          <div class="modal-content" id="ref-modal">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title" id="ref-number">Referral #<%="#{referral.id}" %></h4>
            </div>
          <div class="modal-body">

            <div class="show-referral">
              <ul>
                <li><span>To:</span> <%= referral.referee.name %></li>
                <li>From: <%= referral.referrer.name %></li>

                <li><span>For:</span> <%= referral.patient.name %></li>
                <li><span>When:</span> <%= referral.time %></li>

                <li>Concerns:</li>
                <textarea><%= referral.body%></textarea>
              </ul>
            </div>

            <form id="bloodhound">
              <input class="form-control typeahead1" type="text" id="referral-search" placeholder="Enter your search term">
              <button type="submit" data-provide="typeahead">Search</button>
            </form>

            <iframe></iframe>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>

  </ul>
<% end %>

app/views/patients/home.html.erb
<h1>This is the PATIENT HOME PAGE</h1>

<nav>
  <%= link_to "Return home Doc!", home_patients_path%>
  <%= link_to "Your Referrals", check_referral_patients_path %>
  <%= link_to "Pending Requests", pending_requests_patients_path%>
  <%= link_to "Account Settings", account_settings_patients_path%>
</nav>

app/views/patients/new.html.erb
<h1>This is the sign-up page if you are a NEW PATIENT</h1>
<% if @patient.errors.any? %>
  <ol>
    <% @patient.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @patient do |f| %>
  <fieldset class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control"  %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control"  %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.submit "New Patient" %>
  </fieldset>
<% end %>

app/views/patients/pending_requests.html.erb
<header class="patient-header">
  <h2>Pending Requests</h2>

  <nav class="patient-nav">
    <%= link_to "Home", patient_path(session[:patient_id])%>
    <%= link_to "Your Referrals", check_referral_patients_path %>
    <%= link_to "Pending Requests", pending_requests_patients_path%>
    <%= link_to "Account Settings", account_settings_patients_path%>
    <%= link_to 'Sign Out', login_path, :method => 'delete' %>
  </nav>
</header>

app/views/patients/show.html.erb
<header class="patient-header">
  <h2>Hello, <%= @patient.name %></h2>

  <nav class="patient-nav">
    <%= link_to "Your Referrals", check_referral_patients_path %>
    <%= link_to "Pending Requests", pending_requests_patients_path%>
    <%= link_to "Account Settings", account_settings_patients_path%>
    <%= link_to 'Sign Out', login_path, :method => 'delete' %>
  </nav>
</header>

app/views/patients/show_referral.html.erb
<h2>Referral #<%="#{@referral.id}" %></h2>


  <li>From: <%= @referral.referee.name %></li>
  <li>To: <%= @referral.referrer.name %></li>

  <li>For: <%= @referral.patient.name %></li>
  <li>When: <%= @referral.time %></li>

  <li>Concerns: <%= @referral.body%></li>