config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  #typeahead
  get 'things/typeahead/:query' => 'things#typeahead'

#if someone makes a get request from patient/referrals#forpatient

  resources :patients do
    collection do
      # get 'home', :to => "patients/home"
      get 'check_referral', :to => "patients/check_referral"
      get 'pending_requests', :to => "patients/pending_requests"
      get 'account_settings', :to => "patients/account_settings"
      get 'show_referral', :to => "patients/show_referralrout"
    end
  end


  resources :doctors do
    collection do
      # get 'home', :to => "doctors/home"
      # get 'show', :to => "doctors/home"
      get 'create_referral', :to => "doctors/create_referral"
      get 'pending_requests', :to => "doctors/pending_requests"
      get 'account_settings', :to => "doctors/account_settings"
    end
    resources :referrals
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/doctor.rb
# == Schema Information
#
# Table name: doctors
#
#  id              :integer          not null, primary key
#  name            :text
#  provider_number :text
#  phone           :text
#  dob             :date
#  address         :text
#  email           :text
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Doctor < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :hospitals, :optional => true

  has_many :sent_referrals, class_name: "Referral", foreign_key: "referrer_id"
  has_many :received_referrals, class_name: "Referral", foreign_key: "referee_id"

  validates :email, :presence => true, :uniqueness => true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new (doctor_params)
    # raise 'hell'
    if @doctor.save
      redirect_to doctor_path(session[:doctor_id])
    else
      render :new
    end
  end

  def edit
    # raise "hell"
    @doctor = Doctor.find_by :id => session[:doctor_id]
    # @doctor = Doctor.find params[:id]
  end

  def update
    doctor = Doctor.find_by :id => session[:doctor_id]
    doctor.update doctor_params
    redirect_to doctor_path
  end

  def destroy
  doctor = Doctor.find params[:id]
  doctor.destroy
  redirect_to root_path
  end

  def show
    @doctor = Doctor.find_by :id => session[:doctor_id]
  end

  # def home
  # end
  def pending_requests

  end

  def account_settings
    @doctor = Doctor.find_by :id => session[:doctor_id]
    # raise "hell"
  end

  private
  def doctor_params
    params.require(:doctor).permit(:email, :name, :provider_number, :phone, :dob, :address,:password, :passord_digest, :password_digest_confirmation)
  end
end

app/views/doctors/account_settings.html.erb
<header class="doctor-header">
  <h2 class="doctor-heading">Account Settings</h2>

  <nav class="doctor-nav">
    <%= link_to "Return home Doc!", doctor_path(session[:doctor_id]) %>
    <%= link_to "Create Referral", new_doctor_referral_path(session[:doctor_id])%>
    <%= link_to "Referrals List", doctor_referrals_path(session[:doctor_id]) %>
    <%= link_to "Account Settings", account_settings_doctors_path%>
    <%= link_to 'Sign Out', login_path, :method => 'delete' %>
  </nav>
</header>

<%= form_for @doctor do | f | %>

    <fieldset class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control"%>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :provider_number%>
      <%= f.text_field :provider_number, :class => "form-control"%>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :phone%>
      <%= f.text_field :phone, :class => "form-control"%>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :dob%>
      <%= f.text_field :dob, :class => "form-control"%>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, :class => "form-control"%>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, :class => "form-control"%>
    </fieldset>

    <fieldset class="form-group fsubmit">
      <%= f.submit%>
    </fieldset>
<% end %>

<%= button_to 'Delete Account', doctor_path(@doctor.id), :method => 'delete', :class => "button-delete"%>

app/views/doctors/create_referral.html.erb
<h1>Create a NEW referral DOC!</h1>

app/views/doctors/home.html.erb
<h1>This is the DOCTOR'S HOME PAGE</h1>

<nav>
  <%= link_to "Return home Doc!", home_doctors_path%>
  <%= link_to "Create Referral", create_referral_doctors_path%>
  <%= link_to "Pending Requests", pending_requests_doctors_path %>
  <%= link_to "Account Settings", account_settings_doctors_path%>
</nav>

app/views/doctors/new.html.erb
<h1>This is the sign-up page if you are NEW DOCTOR</h1>
<% if @doctor.errors.any? %>
  <ol>
    <% @doctor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @doctor do |f| %>
  <fieldset class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.submit "New Doctor" %>
  </fieldset>
<% end %>

app/views/doctors/pending_requests.html.erb
<header class="doctor-header">
  <h2 class="doctor-heading">Pending Requests</h2>

  <nav class="doctor-nav">
    <%= link_to "Return home Doc!", doctor_path(session[:doctor_id]) %>
    <%= link_to "Create Referral", new_doctor_referral_path(session[:doctor_id])%>
    <%= link_to "Referrals List", doctor_referrals_path(session[:doctor_id]) %>
    <%= link_to "Account Settings", account_settings_doctors_path%>
    <%= link_to 'Sign Out', login_path, :method => 'delete' %>
  </nav>
</header>

app/views/doctors/show.html.erb
<header class="doctor-header">
  <h2 class="doctor-heading">Hello, Dr. <%= @doctor.name %></h2>

  <nav class="doctor-nav">
    <%= link_to "Create Referral", new_doctor_referral_path(session[:doctor_id])%>
    <%= link_to "Referrals List", doctor_referrals_path(session[:doctor_id]) %>
    <%= link_to "Account Settings", account_settings_doctors_path%>
    <%= link_to 'Sign Out', login_path, :method => 'delete' %>
  </nav>
</header>





<div class="container">
  <div class="journal-container row">
    <div class="bbc col">

    </div>
    <div class="journal2 col">
    </div>

    <div class="journal col">
      <h1>Search for Journals</h1>

        <form id="journal-search">
          <input type="search" id="query" >
          <button id="search">Search</button>
        </form>
    </div>
  </div>
</div>





<!-- HELLO  -->